version: 3
vars:
  codegenJar: "../rmf-codegen/rmf-codegen.jar"
  apiSpecsDir: "../commercetools-api-reference/api-specs"
  generatedDir: "./generated"
  versionId: 1.3.0

tasks:
  build:
    cmds:
      - go build ./...

  fmt:
    cmds:
      - go fmt ./...

  test:
    cmds:
      - go test ./...

  coverage:
    cmds:
      - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - go tool cover -html=coverage.txt

